### PR TITLE
Decentralized Node system

### PR DESCRIPTION
**Pull request by fallengravity**

### CODE REVIEW

**Comment by Dev-JamesR** [comment]
Still Needing Implementation:
1) Penalize miner for false bad node data (faking a node being unavailable)
- Currently miner is penalized for a false positive, meaning they are penalized a block reward if they falsely confirm an out of turn node to be active. The same needs to be implemented for false negatives. (COMPLETED)
2) Address nodeCount bug when nodes are initially deployed or removed (COMPLETED)
3) Fix/Modify/Extend remainder account disbursement length. (COMPLETED)
4) Address node-protocol activation height for live deployment.
5) Bug found in node_validation - intermittent nodes register as inactive or previously inactive/disqualified. This should not register intermittently, should be disqualified until the activity window is exceeded then would qualify for node reward. (Possible fix is setting look-back period to a shorter time frame - 1000 blocks? - the main idea behind the validation look-back is to deter voids concern of someone predicting when their node will be rewarded and only activating prior to that block. This look-back forces longer term node stability and disqualifies unstable or faked nodes) (COMPLETE)

**Comment by fallengravity** [comment]
Issues:

1.) Node Rewards:

It's unclear as to what happened but as soon as I activated my Super node I received a payment of around 73K coins - it looks as the entire remainder fund was deposited into my wallet.

**Comment by Dev-JamesR** [comment]
> Issues:
> 
> 1.) Node Rewards:
> 
> It's unclear as to what happened but as soon as I activated my Super node I received a payment of around 73K coins - it looks as the entire remainder fund was deposited into my wallet.

Yeah, this is something we have to address with live deployment. Currently when the node system goes active at your configuration block height it will dump any rewards into the remainder address if there are zero nodes of that type active. Then when the first node goes live it dumps the remainder address to the one live node that was deployed. We should probably extend the remainder account disbursement period, and also make sure to have the node-protocol block height param correctly set so we have enough nodes active at the activation height for a smooth transition.

**Comment by Dev-JamesR** [comment]
V2 Updates:
We moved completely away from the idea of having miners verify node activity and are now having each node maintain a list of active nodes. Active nodes communicate through the p2p protocol layer to request, send and update active node data so all nodes always have an updated snapshot of node activity. Future updates will likely include using this new communication protocol to help prevent existing attack vectors as it now provides a second layer of block/state verification. 

How does the system work?
1) Each node stores a list of active nodes
2) When a new node comes online and starts syncing blocks, requests are sent out to its own peerset to begin providing updated node activity data.
3) When the nodes own data is up to date/synced it will begin sharing with other nodes that request node activity data.
4) During consensus/reward accumulation, each node pulls from its own synced active node list/data to validate that a node is/has been active prior to reward.
5) Nodes are deployed/registered via smart contract

Still Needs Implementation:
1) Recent node history verification (preventing a node from solely coming online to receive rewards and then disappearing)

**Comment by Dev-JamesR** [comment]
This is outdated development - updated version was merged

**Pull request closed without merging**
